version: '3.8'

services:
  model:
    image: latiefdole/maternal-health-model:latest
    ports:
      - "8080:8080"
      - "8082:8082"
    networks:
      - monitor_net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=satuuntuksemua26@gmail.com
      - GF_SMTP_PASSWORD=1Untuksemua
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=satuuntuksemua26@gmail.com
      - GF_SMTP_FROM_NAME=Grafana Alerts
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitor_net

networks:
  monitor_net:
    driver: bridge
