apiVersion: 1
groups:
  - orgId: 1
    name: Model Monitoring Alerts
    folder: ML Alerts
    interval: 10s
    rules:
      - uid: model_high_traffic
        title: High Traffic Detected
        condition: B
        data:
          - refId: A
            datasourceUid: prometheus_ds
            model:
              expr: sum(rate(mlserver_request_duration_seconds_count[1m]))
              intervalMs: 1000
              maxDataPoints: 43200
          - refId: B
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - A
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: OK
        execErrState: Error
        for: 10s
        annotations:
          summary: "Terdapat lebih dari 0 request pada model. (Bukti Alerting Kriteria 4)"
        labels:
          severity: warning
