apiVersion: 1
contactPoints:
  - orgId: 1
    name: "Email Notification"
    receivers:
      - uid: email_receiver
        type: email
        settings:
          addresses: "satuuntuksemua26@gmail.com"
          singleEmail: true
policies:
  - orgId: 1
    receiver: "Email Notification"
    group_by: ['alertname']
