{
 "title": "latiefdole",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_server_requests_seconds_count[1m])) or sum(rate(http_requests_total[1m])) or sum(rate(scrape_samples_scraped[1m]))",
     "legendFormat": "Requests / Sec"
    }
   ]
  },
  {
   "title": "Model Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"mlflow_model\"}"
    }
   ]
  },
  {
   "title": "Python GC Collections (System Metric)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(python_gc_collections_total[1m])"
    }
   ]
  }
 ]
}